name: readypos_flutter
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  flutter_screenutil: ^5.9.0
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  flutter_animate: ^4.3.0
  page_transition: ^2.1.0
  adaptive_theme: ^3.4.1
  flutter_form_builder: ^9.2.1
  flutter_barcode_scanner: ^2.0.0
  hive_flutter: ^1.1.0
  rive: ^0.12.4
  dotted_border: ^2.1.0
  image_picker: ^0.8.9
  syncfusion_flutter_datagrid: ^24.1.45
  cached_network_image: ^3.3.1
  intl: ^0.18.1
  syncfusion_flutter_charts: ^24.1.45+2
  form_builder_validators: ^9.1.0
  flutter_localizations:
    sdk: flutter
  device_preview: ^1.1.0
  rich_editor: ^0.0.8
  printing: ^5.12.0

  syncfusion_flutter_core: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: null
  flutter_gen_runner: null
  intl_utils: ^2.8.5
  change_app_package_name: ^1.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svgs/
    - assets/pngs/
    - assets/animations/
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish-Medium.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf
        - asset: assets/fonts/Mulish-Bold.ttf

flutter_intl:
  enabled: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
